repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Whitespace & formatting
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
      - id: mixed-line-ending

      # File content checks
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-case-conflict

      # Size checks
      - id: check-added-large-files
        args: ["--maxkb=100"]

      # Repo / Git safety
      - id: forbid-new-submodules
        args: ["--submodule-type=git"]

  # File format and lint checking
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(yaml|yml|md)$

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2
        files: \.md$

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
        files: \.github/workflows/.*\.ya?ml$
